/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	v1beta1 "zookeeper-operator/pkg/apis/zookeeper/v1beta1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeZookeeperClusterLists implements ZookeeperClusterListInterface
type FakeZookeeperClusterLists struct {
	Fake *FakeZookeeperV1beta1
	ns   string
}

var zookeeperclusterlistsResource = v1beta1.SchemeGroupVersion.WithResource("zookeeperclusterlists")

var zookeeperclusterlistsKind = v1beta1.SchemeGroupVersion.WithKind("ZookeeperClusterList")

// Get takes name of the zookeeperClusterList, and returns the corresponding zookeeperClusterList object, and an error if there is any.
func (c *FakeZookeeperClusterLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.ZookeeperClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(zookeeperclusterlistsResource, c.ns, name), &v1beta1.ZookeeperClusterList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ZookeeperClusterList), err
}

// List takes label and field selectors, and returns the list of ZookeeperClusterLists that match those selectors.
func (c *FakeZookeeperClusterLists) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.ZookeeperClusterListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(zookeeperclusterlistsResource, zookeeperclusterlistsKind, c.ns, opts), &v1beta1.ZookeeperClusterListList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ZookeeperClusterListList), err
}

// Watch returns a watch.Interface that watches the requested zookeeperClusterLists.
func (c *FakeZookeeperClusterLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(zookeeperclusterlistsResource, c.ns, opts))

}

// Create takes the representation of a zookeeperClusterList and creates it.  Returns the server's representation of the zookeeperClusterList, and an error, if there is any.
func (c *FakeZookeeperClusterLists) Create(ctx context.Context, zookeeperClusterList *v1beta1.ZookeeperClusterList, opts v1.CreateOptions) (result *v1beta1.ZookeeperClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(zookeeperclusterlistsResource, c.ns, zookeeperClusterList), &v1beta1.ZookeeperClusterList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ZookeeperClusterList), err
}

// Update takes the representation of a zookeeperClusterList and updates it. Returns the server's representation of the zookeeperClusterList, and an error, if there is any.
func (c *FakeZookeeperClusterLists) Update(ctx context.Context, zookeeperClusterList *v1beta1.ZookeeperClusterList, opts v1.UpdateOptions) (result *v1beta1.ZookeeperClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(zookeeperclusterlistsResource, c.ns, zookeeperClusterList), &v1beta1.ZookeeperClusterList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ZookeeperClusterList), err
}

// Delete takes name of the zookeeperClusterList and deletes it. Returns an error if one occurs.
func (c *FakeZookeeperClusterLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(zookeeperclusterlistsResource, c.ns, name, opts), &v1beta1.ZookeeperClusterList{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeZookeeperClusterLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(zookeeperclusterlistsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.ZookeeperClusterListList{})
	return err
}

// Patch applies the patch and returns the patched zookeeperClusterList.
func (c *FakeZookeeperClusterLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.ZookeeperClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(zookeeperclusterlistsResource, c.ns, name, pt, data, subresources...), &v1beta1.ZookeeperClusterList{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.ZookeeperClusterList), err
}
