/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"
	zookeeperv1beta1 "zookeeper-operator/pkg/apis/zookeeper/v1beta1"
	versioned "zookeeper-operator/pkg/client/clientset/versioned"
	internalinterfaces "zookeeper-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "zookeeper-operator/pkg/client/listers/zookeeper/v1beta1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ZookeeperClusterListInformer provides access to a shared informer and lister for
// ZookeeperClusterLists.
type ZookeeperClusterListInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.ZookeeperClusterListLister
}

type zookeeperClusterListInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewZookeeperClusterListInformer constructs a new informer for ZookeeperClusterList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewZookeeperClusterListInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredZookeeperClusterListInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredZookeeperClusterListInformer constructs a new informer for ZookeeperClusterList type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredZookeeperClusterListInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZookeeperV1beta1().ZookeeperClusterLists(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZookeeperV1beta1().ZookeeperClusterLists(namespace).Watch(context.TODO(), options)
			},
		},
		&zookeeperv1beta1.ZookeeperClusterList{},
		resyncPeriod,
		indexers,
	)
}

func (f *zookeeperClusterListInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredZookeeperClusterListInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *zookeeperClusterListInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&zookeeperv1beta1.ZookeeperClusterList{}, f.defaultInformer)
}

func (f *zookeeperClusterListInformer) Lister() v1beta1.ZookeeperClusterListLister {
	return v1beta1.NewZookeeperClusterListLister(f.Informer().GetIndexer())
}
